# Name of the GitHub Actions workflow
name: Scan with OWASP Dependency Check

on:
  # Trigger the workflow on the following events:
  push:
    branches: ["main"]

# Define the job(s) to be executed within the workflow
jobs:
  depchecktest:
    name: Scan with OWASP Dependency Check

    runs-on: [ 'ubuntu-latest' ] # Use the latest version of Ubuntu

    permissions:
      actions: read
      contents: write # Needed to commit files to the repository
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Scan with OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Mutillidae' # Project name for Dependency Check
          path: '.' # Scan all files in the current directoryy
          format: 'CSV' # Output format for scan results
          out: '.' # Output directory (default is the current directory)
          args: >
            --enableRetired # Additional scan arguments for Dependency Check
        continue-on-error: true

      - name: Commit CSV report to main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          mv dependency-check-report.csv owasp-dependency-check.csv
          git add owasp-dependency-check.csv
          git commit -m "Add OWASP Dependency Check CSV report"
          git push origin main
